### ISSUE TITLE
Issue with the input box above the picker calender.

### ISSUE THREAD

**Issue by rbeach4** [talentedandrew/react-modern-datepicker#11]
Good morning, 

I have been using the modern-datepicker in this repo for our application and i am having an issue with typing in text inside of the input box. What would be the odds you could add a switch or flag to turn that on and off?

Ricky

**Comment by talentedandrew** [comment]
@rbeach4 do you need a feature where in a user can manually type a date?

**Comment by rbeach4** [comment]
@talentedandrew yes that is correct. could you update the repo with that feature and roll out a new version?

**Comment by talentedandrew** [comment]
@rbeach4 sure will do but can you please tell how would it behave? Like what if a user types something which is not date? Should it have a pattern or something like that?

**Comment by talentedandrew** [comment]
@rbeach4 do you want something like this?


![react-modern-datepicker](https://user-images.githubusercontent.com/15646138/62488741-b47b9280-b7e2-11e9-967c-04c0a2494bb1.gif)

**Comment by rbeach4** [comment]
yes that is correct!
