### ISSUE TITLE
styled-components warning

### ISSUE THREAD

**Issue by rdjakovic** [talentedandrew/react-modern-datepicker#6]
In console there is a warning:
"styled-components.browser.esm.js:1716 Warning: The "extend" API will be removed in the upcoming v4.0 release. Use styled(StyledComponent) instead. You can find more information here: https://github.com/styled-components/styled-components/issues/1546"

**Comment by talentedandrew** [comment]
@rdjakovic Thanks for the info. Will look into it and resolve it ASAP.
